### ISSUE TITLE
Create a discovery mechanism

### ISSUE THREAD

**Issue by meisenzahl** [manexim/libirobot#1]

**Comment by meisenzahl** [comment]
@aimproxy I've implemented something before to make it easier for you to get started. I hope you can do something with it.

There is the tool `cli`. It should show a message when an iRobot is found on the network. **The message appears at least once, because the discovery message sent is also received!** So if the message **Found new robot** appears more than once, it should already be the response from your iRobot.

Let me know if I can help you.

**Comment by aimproxy** [comment]
I compile it, How should I run it now? How I call cli?

**Comment by meisenzahl** [comment]
You can call it from the `build` folder with `./src/cli`. I updated the `README` accordingly.

Also, the message should now only be displayed when an iRobot replies.

**Comment by aimproxy** [comment]
It's works, we prints "Found new robot"

**Comment by meisenzahl** [comment]
Glad to hear it seems to be working. [I just uploaded a change](https://github.com/manexim/libirobot/commit/dd8fa73da15e148c123bdb48f48c31c4bf966144). Does the current version now show you a valid JSON string?

**Comment by aimproxy** [comment]
Looks fine
```
Found new robot: {"ver":"3","hostname":"Roomba-3178480822035600","robotname":"e5","ip":"192.168.1.94","mac":"D0:C5:D3:BD:21:31","sw":"3.4.46","sku":"e515840","nc":0,"proto":"mqtt","cap":{"ota":1,"eco":1,"svcConf":1}}
```

**Comment by meisenzahl** [comment]
I hope you get on from there. Let me know if you need any help.

**Comment by aimproxy** [comment]
Thanks, I will take the path from there, thx for the help on this discovery! kkk :)
