### ISSUE TITLE
Establishing a TLS client connection

### ISSUE THREAD

**Issue by aimproxy** [manexim/libirobot#2]
@meisenzahl Hi, I allready have some code, at this point I need link the device, so I try to establish a TLS socket connection...

#### Code from `dorita980`
```js
function checkV2 () {
  var sliceFrom = 13;
  discovery.getRobotPublicInfo(host, function (e, robotData) {
    console.log('Robot Data:');
    console.log(robotData);
  });
  const packet = 'f005efcc3b2900';
  var client = tls.connect(8883, host, {rejectUnauthorized: false, ciphers: 'AES128-SHA256'}, function () {
    client.write(new Buffer(packet, 'hex'));
  });

  client.on('data', function (data) {
    if (data.length === 2) {
      sliceFrom = 9;
      return;
    }
    if (data.length <= 7) {
      console.log('Error getting password. Follow the instructions and try again.');
    } else {
      console.log('Password=> ' + new Buffer(data).slice(sliceFrom).toString() + ' <= Yes, all this string.');
      console.log('Use this credentials in dorita980 lib :)');
    }
    client.end();
    process.exit(0);
  });

  client.setEncoding('utf-8');
}
```

And this is my code
```vala
public async void link_device (InetAddress address, Cancellable cancellable) {

    const uint16 port = 8883;
    const string packet = "f005efcc3b2900";
    const string cipher = "AES128-SHA256";

    try {

      // Connect:
      SocketClient client = new SocketClient ();
      //client.set_tls (true);
      //client.set_tls_validation_flags (GLib.TlsCertificateFlags.GENERIC_ERROR);


      SocketConnection conn = yield client.connect_async (
        new InetSocketAddress (address, port), cancellable);

    } catch (Error e) {
      print ("Error: %s\n", e.message);
    }
  }
}
```

So, I don't know how to use cipher to establish a connect to the TLS Socket !?:..

**Comment by aimproxy** [comment]
If `client.set_tls (true);` is set I receive this `Error: Unacceptable TLS certificate`...

**Comment by meisenzahl** [comment]
Take a look at https://valadoc.org/gio-2.0/GLib.SocketClient.html. If you activate TLS with [`tls = true`](https://valadoc.org/gio-2.0/GLib.SocketClient.set_tls.html) you can connect to the [`accept_certificate`](https://valadoc.org/gio-2.0/GLib.TlsConnection.accept_certificate.html) signal and return `true` to accept the certificate.

I hope this helps :)

**Comment by aimproxy** [comment]
```vala
      // Init Tls Conn
      var tls_conn = new GLib.TlsConnection ().from_file ();

      tls_conn.accept_certificate.connect((cert, err) => {

      });
```

Yeah, but where I find a certificate now !?

**Comment by meisenzahl** [comment]
> ```js
>   var client = tls.connect(8883, host, {rejectUnauthorized: false, ciphers: 'AES128-SHA256'}, function () {
> ```

I think `rejectUnauthorized: false` does not validate the certificate in dorita980 either. So it seems you can ignore the certificate.

> ```vala
> tls_conn.accept_certificate.connect((cert, err) => {
>     return true;
> });
> ```

In your code you should `return true;`.

**Comment by aimproxy** [comment]
Yeah, I also think about this, so I tried, and we give me nothing ..., the command line just doesn't print anything even a error, so I think is good! Now how about cipher ??

I find this `GCrypt.Cipher.Algorithm.AES128` but I don't know how to implement this and if is needed!?

**Comment by meisenzahl** [comment]
I'm not sure if you need to set a cipher. But since I didn't find anything in the documentation of [GLib.TlsConnection](https://valadoc.org/gio-2.0/GLib.TlsConnection.html) or [GLib.TlsClientConnection](https://valadoc.org/gio-2.0/GLib.TlsClientConnection.html), I would try it without a cipher ;)

**Comment by aimproxy** [comment]
OK, but how about the `client.write(new Buffer(packet, 'hex'));` It's `DataInputStream` do this job?

**Comment by meisenzahl** [comment]
I didn't know the [`DataInputStream`](https://valadoc.org/gio-2.0/GLib.DataInputStream.html) class yet. Therefore I implemented my own [helper class to work with the binary data](https://github.com/manexim/home/blob/develop/src/utils/Buffer.vala). It is based on the [`Buffer` class from Node.js](https://nodejs.org/api/buffer.html).

But [`DataInputStream`](https://valadoc.org/gio-2.0/GLib.DataInputStream.html) should do the job too.

**Comment by aimproxy** [comment]
Establish a socket connection is done, now is time to setup the TLS, so I saw Vala have a class called GnuTLS. This class is a lack of documentation but alright, I saw some C example code and I did it, now I just want ask you how to use delegate types, I saw the gnome docs but when I tried it doesn't work.

[This one](https://valadoc.org/gnutls/GnuTLS.set_log_function.html) `GnuTLS.set_log_function(LogFunc func)` requires a LogFunc wish is a delegate, so I created a print function, you can see below, so now how I implement this throw this delegate type?
I'm get confusing!

The [delegate](https://valadoc.org/gnutls/GnuTLS.LogFunc.html):
```
public delegate void LogFunc (int level, string msg) 
```

The print function:
```
void print_logs(int level, string msg)
{
    printf("GnuTLS [%d]: %s", level, msg);
}
```

**Comment by meisenzahl** [comment]
I'm not quite sure if I understand you correctly. What do you mean by "*Establish a socket connection is done*"? Can you send a message to your Roomba and he's already responding? For example, can you start it?

Have you already uploaded your code to GitHub in a fork? Then I could take a closer look at your progress.

For delegates take a look at:

- https://wiki.gnome.org/Projects/Vala/Manual/Delegates
- https://wiki.gnome.org/Projects/Vala/Tutorial#Delegates

**Comment by aimproxy** [comment]
Hi, whats I mean by establish a socket connection is done is through GLib Socket I successful connect to the Roomba, and I receive a MSG but is encoded!

So it's time to implement GnuTLS!! I initiate  GnuTLS and create a Session is pointing to the GLib Socket during connection. 
Next I setup ciphers like `dorita` does and finally is I need now send the `packet` through the TLS socket but the packet is a string and like `dorita` the buffer will encode into an hex value, and send to the TLS socket. After this we receive data from the roomba wish is the final part.

The buffer you have write is not capable to encode the string to an hex value, so I'm changing that too...

What's I'm asking you about delegates is to help me see the logs, I don't know how delegates work, I need read the docs more careful!

Resuming: The progress until know is just received and encoded string from the roomba!
